### ISSUE TITLE
ModuleNotFoundError: No module named 'tools' 

### ISSUE THREAD

**Issue by zhouzk5** [xh-liu/SDG_code#1]
Hello.
I met the following trouble when i running the scripts/sample.py, and I've made a lot of effort to solve it, but can't.
`Traceback (most recent call last):
  File "/mnt/SSD_1T/zhouzikang/project/SDG/scripts/sample.py", line 31, in <module>
    from tools.get_text import get_ffhq_text
ModuleNotFoundError: No module named 'tools'
`
Thanks for your help.

and then I want to solve this problem by this way:
`pip install tools`
but there another bug appearance:
`Traceback (most recent call last):
  File "/mnt/SSD_1T/zhouzikang/project/SDG/scripts/sample.py", line 31, in <module>
    from tools.get_text import get_ffhq_text
ModuleNotFoundError: No module named 'tools.get_text'`
How can I solve this problem, looking forward to your reply would be much appreciated！ @xh-liu

**Comment by xh-liu** [comment]
Thank you for pointing out the issue! I have fixed it in the repo.
